### ISSUE TITLE
6月のtech talks

### ISSUE THREAD

**Issue by kumabook** [axxxxs2011/tech_talks#5]
6/16 Friday

**Comment by kumabook** [comment]
@magicant そういえば場所の確保ってしたんだっけ？

**Comment by kasaharu** [comment]
@kumabook 
まじかんとが確保してくれてたよ

**Comment by magicant** [comment]
部屋を取ったことを自分で忘れているアカウントがこちらになります

**Comment by kumabook** [comment]
フリートークのネタ

- https://github.com/tokio-rs/tokio

**Comment by skirino** [comment]
気になる。
https://en.wikipedia.org/wiki/Google_Fuchsia

**Comment by kumabook** [comment]
https://github.com/axxxxs2011/tech_talks/wiki/tech_talk_20170616

に覚えている限りの話した内容を追加
