### ISSUE TITLE
9月のtech talks

### ISSUE THREAD

**Issue by kumabook** [axxxxs2011/tech_talks#8]
9/27とか29 とか

**Comment by kumabook** [comment]
@magicant 9/27とか29とか場所空いてませんかね？

**Comment by magicant** [comment]
9/27 18:00 で確保してみた

**Comment by kumabook** [comment]
あざます！
では、日にちはそこで！

**Comment by skirino** [comment]
transactionの話の続きやりまーす。(希望者多ければ譲ります)

**Comment by magicant** [comment]
> 9/27 18:00

とても残念なことに社内プレゼン大会 & ビアバッシュと被ってしまった

9/29 も部屋は空いてるが、無理に同じ週にやらんでも…という気もする

**Comment by magicant** [comment]
9/29 は秋葉原フォーラムらしい

**Comment by kumabook** [comment]
来週, 9/20~9/22あたりはどう？

**Comment by magicant** [comment]
9/21 18:00 にしてみた

**Comment by skirino** [comment]
9/21でOKです!

**Comment by magicant** [comment]
あれ、 @irxground は来ないのか

**Comment by skirino** [comment]
[9/22開催した](https://github.com/axxxxs2011/tech_talks/wiki/tech_talk_20170922)。10月分を作るだけ作っておきました。
closeします。
