### ISSUE TITLE
10月のtech talks

### ISSUE THREAD

**Issue by skirino** [axxxxs2011/tech_talks#9]
日時未定だけどどこかでやるぞ。

**Comment by kumabook** [comment]
10/18 か10/19がいいっす！

**Comment by magicant** [comment]
10/18 (水) 18:00 で部屋取ってみた

**Comment by skirino** [comment]
あざーす! 行けると思います。

**Comment by magicant** [comment]
明後日ですが、お客さんくるみたいなんで時間を 18:30 からに変更します

**Comment by kumabook** [comment]
🙆‍♂️

**Comment by kumabook** [comment]
小ネタですが、server side swift で music barのアプリを作った話をします。15分くらいのネタかなと思います。

**Comment by kumabook** [comment]
@pankona http://pankona.github.io/slides/golang_tokyo_201709.html とか話してくれません？

**Comment by pankona** [comment]
@kumabook
いいですよー！所要時間はおよそ 10 分ちょいかと思います。

**Comment by kumabook** [comment]
https://kumabook.github.io/slides/?name=bar_app

**Comment by kumabook** [comment]
https://github.com/axxxxs2011/tech_talks/wiki/tech_talk_20171019
を作成しました。
